// Generated by cpp11: do not edit by hand
// clang-format off

#include "lua51_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void fun();
extern "C" SEXP _lua51_fun() {
  BEGIN_CPP11
    fun();
    return R_NilValue;
  END_CPP11
}
// code.cpp
external_pointer<lua_State, close_lua> open_lua();
extern "C" SEXP _lua51_open_lua() {
  BEGIN_CPP11
    return cpp11::as_sexp(open_lua());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_lua51_fun",      (DL_FUNC) &_lua51_fun,      0},
    {"_lua51_open_lua", (DL_FUNC) &_lua51_open_lua, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_lua51(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
